#spring:
#  config:
#    active:
#      on-profile: default
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root1234
#mybatis:
#  mapper-locations:
#    classpath:mapper/**.xml # **.xml: 해당 경로 아래 모든 xml 파일
#  configuration:
#    map-underscore-to-camel-case: true
---
spring:
  config:
    active:
      on-profile: default
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: oracle
mybatis:
  mapper-locations:
    mapper/*Mapper.xml
  type-aliases-package : guzzi.project.vo
logging:
  level:
    guzzi.project.mapper : Trace



---



#mybatis:
#  configuration:
#    multiple-result-sets-enabled: false
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
#    jdbc-type-for-null: varchar
#    default-fetch-size: 500
#  mapper-locations:
#    - classpath:mybatis/mapper/*.xml
